config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#checksum_generator'

  resource :pages, only: [] do
    member do
      post :submit_checksum_generator
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  require 'checksum_generator'

  before_action :authenticate_user!
  before_action :load_checksum, :build_checksum, only: [:submit_checksum_generator]

  private

  def load_checksum
    @cg = ChecksumGenerator.new(params[:content]).generate
  end

  def build_checksum
    number_of = @cg[:number_of]
    @checksum = "#{number_of[:original_words]}-#{number_of[:newly_created_words]}-" +
                "#{number_of[:upper_case_vowels]}-#{number_of[:consonants]}-#{number_of[:original_characters]}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Checksum Generator
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag 'favicon.ico'
  %body{class: "#{params[:controller].gsub("/", "-")}"}
    = render "shared/flash"
    = render "shared/header"
    .container-fluid
      = yield
    = render "shared/footer"  
    %script{type: "text/javascript", 'data-turbolinks-eval'=>false}
      var string = "#{(j (yield :scripts))}";
      eval(string);

app/views/pages/checksum_generator.html.haml
.container
  %br
  %br
  %br	
  %h2.text-xs-center Generator
  .row
    .col-xs-12.col-sm-8.col-sm-offset-2.col-md-6.col-md-offset-3.col-lg-6.col-lg-offset-3.col-xl-6.col-xl-offset-3
      = form_tag(submit_checksum_generator_pages_path, method: :post, remote: true) do
        %fieldset{class: "form-group"}
          %label Content
          = text_area_tag :content, '', class: "form-control", required: true
        = submit_tag "Generate", class: "btn btn-primary btn-block"
  %br
  %br
  %br
  .row
    .col-12
      %p.value

app/views/pages/submit_checksum_generator.js.haml
$('.value').text("Generated Checksum: #{@checksum}");

app/views/shared/_flash.html.haml
- message = ""
- flash_class = ""
- if flash[:notice].present?
  - message = flash[:notice]
  - flash_class = "alert-success"
- elsif flash[:error].present?
  - message = flash[:error]
  - flash_class = "alert-danger"
  - title = "Error!"
- elsif flash[:success].present?
  - message = flash[:success]
  - flash_class = "alert-success"
  - title = "Success!"

.alert.in#flash{class: flash_class}
  %button.close{"aria-label" => "Close", "data-dismiss" => "alert", type: "button"}
    %span{"aria-hidden" => "true"} ×
  %h4= title
  %p= message
= content_for :scripts do
  window.checksumgenerator.shared.init_flash("#{message}");

app/views/shared/_footer.html.haml
%footer.footer.navbar-fixed-bottom
  .container.text-center
    %span.text-muted
      Created by
      %b Norbert Forman

app/views/shared/_header.html.haml
%nav.navbar.navbar-light.navbar-fixed-top.bg-faded
  .container
    = link_to "Checksum Generator", root_path, class: "navbar-brand"
    %ul.nav.navbar-nav.pull-right
      - if current_user.blank?
        %li.nav-item
          = link_to "Sign In / Sign Up", new_user_session_path(), class: "nav-link"
      - if current_user.present?
        %li.nav-item.dropdown
          %a.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", href: "#", role: "button"}
            = current_user.email
          .dropdown-menu
            = link_to "Profile", edit_user_registration_path(), class: "dropdown-item"
            = link_to "Sign out", destroy_user_session_path(), method: :delete, class: "dropdown-item"